### ISSUE TITLE
Should add entropy thresholding in SWEET detection

### ISSUE THREAD

**Issue by hongcheki** [mignonjia/TS_watermark#1]
Hi, thanks for the great repo.

Unfortunately, I found a bug in the SWEET implementation.

According to the original SWEET paper and its repository, entropy thresholding is applied during the generation phase **and detection phase.**

However, in your implementation reproducing the SWEET method, lines for applying entropy threshold are omitted in the detection phase.
(c.f., implementation in original SWEET code is here: https://github.com/hongcheki/sweet-watermark/blob/master/sweet.py#L100)

Is it the code you used for your experiments?

If this code is used in your paper's experiment, and if you also identify it as a bug, please consider fixing it and rerun experiments.

Thank you.

**Comment by mignonjia** [comment]
Thanks for highlighting this issue! 

The reason it wasn't implemented during the detection phase is due to a common scenario in invisible watermarking for general-purpose generation, where the prompt is not visible during detection. But we will run SWEET experiments when prompts are given during detection and add it into the next version of our manuscript! Does that approach sound good to you?

**Comment by hongcheki** [comment]
Thanks for the kind reply and for including a complete version of SWEET in the next version of the manuscript.

We respectfully argue that **applying the entropy threshold only in the generation phase but not in the detection phase is not an intuition that SWEET holds.** That modified implementation will undoubtedly show a lower 'green token ratio' as the watermark is only partially embedded in the text used in detection.
SWEET's central intuition is that excluding low-entropy tokens by reproducing entropy information in the detection phase will enable better watermark detection since the watermark cannot be embedded in too spiky distribution. Thus, we believe that **the current implementation of SWEET in this paper is modified intentionally and the modification should be explicitly mentioned in the paper.** It is just an another watermarking method that shares SWEET's idea in generation phase.

We acknowledge that the SWEET method needs the exact prompt to reproduce the entropy completely, and it has limitations in practical settings. (In the updated version of the SWEET paper, authors presented SWEET results without exact prompts, which still shows better performance) **Nevertheless, We request full implementation of SWEET to be the baseline if it is to be compared with TS-watermark and KGW.**

We are also very much interested in watermark in the general text domain, and how SWEET performs in there. We appreciate your work and for regarding SWEET as a baseline. Thank you.

**Comment by mignonjia** [comment]
We just uploaded the revised baselines in this repo, and will update arXiv in a few days. We use `SWEET_no_prompt` to represents the baseline where the detection algorithm only use the generated tokens to compute entropy, instead of using both the prompt and the generated tokens. 

Check [result_figures.ipynb](https://github.com/mignonjia/TS_watermark/blob/main/result_figures.ipynb) for the new results and [inference_sweet.py](https://github.com/mignonjia/TS_watermark/blob/main/inference_sweet.py) and [inference_sweet_no_prompt.py](https://github.com/mignonjia/TS_watermark/blob/main/inference_sweet_no_prompt.py) for the implementation.
 
Feel free to point out any further concerns!

**Comment by hongcheki** [comment]
Thank you for updating SWEET baseline!

Best regards,
